apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
  namespace: dev
  annotations:
    argocd-image-updater.argoproj.io/image-list: sharanalwars/flask
    argocd-image-updater.argoproj.io/sharanalwars/flask.tag: semver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
      - name: flask-app
        image: sharanalwars/flask:latest
        ports:
        - containerPort: 5000
        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "256Mi"
            cpu: "500m"
