apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
  namespace: dev
  annotations:
    # Tells Image Updater to watch this repository
    argocd-image-updater.argoproj.io/image-list: "sharanalwars/flask"
    # Semantic versioning for updating the tag
    argocd-image-updater.argoproj.io/sharanalwars/flask.tag: "semver"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
      - name: flask-app
        image: "sharanalwars/flask:latest"
        ports:
        - containerPort: 5000