apiVersion: v1
kind: Service
metadata:
  name: flask-app-service
  namespace: dev
spec:
  selector:
    app: flask-app
  ports:
  - protocol: TCP
    port: 80         # Port exposed by the Service
    targetPort: 5000 # Port on the Flask container
    nodePort: 30001  # Optional: Specify a static NodePort (30001 in this case)
  type: NodePort
