# Base image
FROM python:3.9-slim

# Set the working directory in the container
WORKDIR /app

# Copy requirements.txt into the container
COPY requirements.txt .

# Install Python dependencies
RUN pip install --no-cache-dir -r requirements.txt

RUN pip install python-dotenv

# Copy the application code into the container
COPY . .

# Expose the application port
EXPOSE 5000

# Run the application
CMD ["python", "app.py"]